### ISSUE TITLE
loading error on "DefineClones.py bygroup  -h"

### ISSUE THREAD

**Issue by ssnn-airr** [immcantation/changeo#16]
**[Original report](https://bitbucket.org/kleinstein/changeo/issues/16) by Anonymous.**

----------------------------------------

Maybe my installation (on local machine, MacOS) isn't done properly, but this is output: 

----------------------------
Error in dyn.load("SHMDistance.so") : 
  unable to load shared object '/Users/soniat/src/repos/changeo/rlib/SHMDistance.so':
  dlopen(/Users/soniat/src/repos/changeo/rlib/SHMDistance.so, 6): no suitable image found.  Did find:
	/Users/soniat/src/repos/changeo/rlib/SHMDistance.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
Traceback (most recent call last):
  File "/Users/soniat/src/repos/changeo/DefineClones.py", line 46, in <module>
    SHMClones = STAP(r_script, 'SHMClones')
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rpy2/robjects/packages.py", line 256, in __init__
    reval(string, env)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rpy2/robjects/packages.py", line 66, in reval
    res = _reval(p, envir = envir)
rpy2.rinterface.RRuntimeError: Error in dyn.load("SHMDistance.so") : 
  unable to load shared object '/Users/soniat/src/repos/changeo/rlib/SHMDistance.so':
  dlopen(/Users/soniat/src/repos/changeo/rlib/SHMDistance.so, 6): no suitable image found.  Did find:
	/Users/soniat/src/repos/changeo/rlib/SHMDistance.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
--------------------------------------------------------

**Comment by ssnn-airr** [comment]
**Original comment by Anonymous.**

----------------------------------------

This worked for me :

.... build the distance library on Os X: (in changeo repo dir)
gcc -c -fPIC SHMDistance.c -o SHMDistance.o
gcc -shared -Wl,-dylib_install_name,SHMDistance.so -o SHMDistance.so SHMDistance.o

**Comment by ssnn-airr** [comment]
**Original comment by Jason Vander Heiden (Bitbucket: [javh](https://bitbucket.org/javh), GitHub: [javh](https://github.com/javh)).**

----------------------------------------

SHMDistance.c compile on Os X worked.
