### ISSUE TITLE
DefineClones fails to execute with "bygroup --model aa"

### ISSUE THREAD

**Issue by ssnn-airr** [immcantation/changeo#18]
**[Original report](https://bitbucket.org/kleinstein/changeo/issues/18) by Jason Vander Heiden (Bitbucket: [javh](https://bitbucket.org/javh), GitHub: [javh](https://github.com/javh)).**

----------------------------------------

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
PID 30107:  Error in sibling process detected. Cleaning up.
PID 30108:  Error in sibling process detected. Cleaning up.
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jason/workspace/igpipeline/changeo_v0.4/DefineClones.py", line 496, in processQueue
    clones = clone_func(records, **clone_args) if data else None
  File "/home/jason/workspace/igpipeline/changeo_v0.4/DefineClones.py", line 241, in distanceClones
    dists = squareform(dists)
  File "/usr/lib64/python2.7/site-packages/scipy/spatial/distance.py", line 1481, in squareform
    is_valid_dm(X, throw=True, name='X')
  File "/usr/lib64/python2.7/site-packages/scipy/spatial/distance.py", line 1570, in is_valid_dm
    'be zero.') % name)
ValueError: Distance matrix 'X' diagonal must be zero.
```

**Comment by ssnn-airr** [comment]
**Original comment by Namita Gupta (Bitbucket: [namita1025](https://bitbucket.org/namita1025), GitHub: [namita1025](https://github.com/namita1025)).**

----------------------------------------

X scoring was mistakenly 0, is now 1 so all amino acids are considered matches

**Comment by ssnn-airr** [comment]
**Original comment by Ang Cui (Bitbucket: [angcui](https://bitbucket.org/angcui), GitHub: [angcui](https://github.com/angcui)).**

----------------------------------------

Still experiencing the issue in the 3/13/15 version

Command used: DefineClones.py bygroup -d <file> --model aa --dist 10

**Comment by ssnn-airr** [comment]
**Original comment by Namita Gupta (Bitbucket: [namita1025](https://bitbucket.org/namita1025), GitHub: [namita1025](https://github.com/namita1025)).**

----------------------------------------

Issue was that score of X with itself was non-zero. Fixed by not calculating distance between junction and itself anymore, so diagonal of distance matrix asserted to be zero.
