### ISSUE TITLE
createGermlines.py error

### ISSUE THREAD

**Issue by ssnn-airr** [immcantation/changeo#192]
**[Original report](https://bitbucket.org/kleinstein/changeo/issues/192) by Kelly Dew-Budd (Bitbucket: [Kelly Dew-Budd](https://bitbucket.org/Kelly Dew-Budd), ).**

----------------------------------------

Can you help me find the source of this error? 

```shell
 START> CreateGermlines
 FILE> scoper_out_20220705_21:32:10.tsv
 GERM_TYPES> dmask
 SEQ_FIELD> sequence_alignment
   V_FIELD> v_call
   D_FIELD> d_call
   J_FIELD> j_call
    CLONED> False

Traceback (most recent call last):
  File "/usr/local/bin/CreateGermlines.py", line 354, in <module>
    createGermlines(**args_dict)
  File "/usr/local/bin/CreateGermlines.py", line 148, in createGermlines
    for key, records in receptor_iter:
  File "/usr/local/bin/CreateGermlines.py", line 133, in <genexpr>
    receptor_iter = ((x.sequence_id, [x]) for x in db_iter)
  File "/usr/local/lib/python3.9/site-packages/changeo/IO.py", line 75, in __next__
    record = next(self.reader)
  File "/usr/local/lib/python3.9/site-packages/airr/io.py", line 99, in __next__
    raise ValueError('row has extra data')
ValueError: row has extra data
```

Thank you

**Comment by ssnn-airr** [comment]
**Original comment by Kelly Dew-Budd (Bitbucket: [Kelly Dew-Budd](https://bitbucket.org/Kelly Dew-Budd), ).**

----------------------------------------

Fixed it. The column names shifted to the right when saving the output from R. `row.names = FALSE` will be ingrained into my head forever.

‌
