### ISSUE TITLE
Division by zero error in AnalyzeAa

### ISSUE THREAD

**Issue by ssnn-airr** [immcantation/changeo#39]
**[Original report](https://bitbucket.org/kleinstein/changeo/issues/39) by Jason Vander Heiden (Bitbucket: [javh](https://bitbucket.org/javh), GitHub: [javh](https://github.com/javh)).**

----------------------------------------

Grab the file from me...

```
START> AnalyzeAa
 FILE> AAYFK_KS004P_db-pass.tab

PROGRESS> 15:34:19 [                    ]   0% (     0) 0.0 min/usr/lib64/python2.7/site-packages/Bio/Seq.py:2040: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  BiopythonWarning)
PROGRESS> 15:34:20 [###                 ]  15% ( 2,337) 0.0 minTraceback (most recent call last):
  File "/home/jason/workspace/igpipeline/changeo/bin/AnalyzeAa.py", line 225, in <module>
    analyzeAa(**args_dict)
  File "/home/jason/workspace/igpipeline/changeo/bin/AnalyzeAa.py", line 152, in analyzeAa
    aacdr3 = cdr3Properties(row['JUNCTION'], out_args)
  File "/home/jason/workspace/igpipeline/changeo/bin/AnalyzeAa.py", line 71, in cdr3Properties
    cdr3['CDR3_AA_POSITIVE'] = round(100*float(len(re.findall("[RK]", cdr3_aa)))/cdr3['CDR3_AA_LENGTH'], 2)
ZeroDivisionError: float division by zero
```

**Comment by ssnn-airr** [comment]
**Original comment by Namita Gupta (Bitbucket: [namita1025](https://bitbucket.org/namita1025), GitHub: [namita1025](https://github.com/namita1025)).**

----------------------------------------

If sequence field has length 0 or non-multiple of 3, that record fails analysis
