### ISSUE TITLE
IMGT/V-QUEST

### ISSUE THREAD

**Issue by ssnn-airr** [immcantation/changeo#72]
**[Original report](https://bitbucket.org/kleinstein/changeo/issues/72) by Robert Amezquita (Bitbucket: [Robert A. Amezquita](https://bitbucket.org/Robert A. Amezquita), ).**

----------------------------------------

Error with using IMGT/V-QUEST (not the HighV-QUEST) output. The resulting output (selecting C. Excel File, with outputs 1, 2, 3, 6 selected) seems to be missing a column for SEQUENCE. Might just be something that can be munged and added as an "aligner" option..?

[ra364@localhost changeo]$ MakeDb.py imgt -i ../imgt/ko_vquest.zip -s ../sequences/ko_seqs.fasta
        START> MakeDb
      ALIGNER> IMGT
ALIGN_RESULTS> ../imgt/ko_vquest.zip
     SEQ_FILE> ko_seqs.fasta
     NO_PARSE> False
 SCORE_FIELDS> False
REGION_FIELDS> False
 
Traceback (most recent call last):
  File "/home/ra364/.local/bin/MakeDb.py", line 1020, in <module>
    args.func(**args_dict)
  File "/home/ra364/.local/bin/MakeDb.py", line 886, in parseIMGT
    score_fields=score_fields, region_fields=region_fields, out_args=out_args)
  File "/home/ra364/.local/bin/MakeDb.py", line 728, in writeDb
    for record in db_gen:
  File "/home/ra364/.local/bin/MakeDb.py", line 538, in readIMGT
    'SEQUENCE_INPUT': sm['Sequence']}
KeyError: 'Sequence'

**Comment by ssnn-airr** [comment]
**Original comment by Jason Vander Heiden (Bitbucket: [javh](https://bitbucket.org/javh), GitHub: [javh](https://github.com/javh)).**

----------------------------------------

So, it does indeed look like the field is missing in both "normal" V-QUEST and "indel" V-QUEST mode.  I think the thing to do is just note in the docs that MakeDb-imgt only works with HighV-QUEST.  I don't think maintaining separate V-QUEST support is worth it, especially if IMGT is going to continue to change the output.

**Comment by ssnn-airr** [comment]
**Original comment by Namita Gupta (Bitbucket: [namita1025](https://bitbucket.org/namita1025), GitHub: [namita1025](https://github.com/namita1025)).**

----------------------------------------

Updated documentation to reflect V-QUEST is not supported in 6075a17913f7
