### ISSUE TITLE
MakeDb.py returns error

### ISSUE THREAD

**Issue by ssnn-airr** [immcantation/changeo#93]
**[Original report](https://bitbucket.org/kleinstein/changeo/issues/93) by Eric Mukherjee (Bitbucket: [emukherj](https://bitbucket.org/emukherj), ).**

----------------------------------------

I have an IMGT output of 12 sequences I'm trying to make a Db out of, but when I run it, this happens:

C:\Users\Infin\Desktop\HammersSequences>MakeDb.py imgt -i IMGToutput.zip -s SequencesVH.fasta --regions --scores
Traceback (most recent call last):
  File "C:\Users\Infin\Anaconda3\Scripts\MakeDb.py", line 23, in <module>
    from changeo.IO import countDbFile, extractIMGT, getDbWriter, readRepo
  File "C:\Users\Infin\Anaconda3\lib\site-packages\changeo\IO.py", line 24, in <module>
    csv.field_size_limit(sys.maxsize)
OverflowError: Python int too large to convert to C long

I'm using Windows 10, Python 3.6.0 as part of Anaconda 4.3.1 64-bit

**Comment by ssnn-airr** [comment]
**Original comment by Eric Mukherjee (Bitbucket: [emukherj](https://bitbucket.org/emukherj), ).**

----------------------------------------

Seems like the problem is that in Windows, long is always 32-bit. Even if I manually edit IO.py to set the limit to 1000000, the following happens: 

C:\Users\Infin\Desktop\HammersSequences>MakeDb.py imgt -i IMGToutput.zip -s SequencesVH.fasta --regions --scores
usage: MakeDb.py [-h] [--version]  ...
MakeDb.py: error: the following arguments are required:


...and no arguments are listed

**Comment by ssnn-airr** [comment]
**Original comment by Jason Vander Heiden (Bitbucket: [javh](https://bitbucket.org/javh), GitHub: [javh](https://github.com/javh)).**

----------------------------------------

Hey @emukherj, I'm investigating this, but I have to setup a Windows/Anaconda environment to do so and that might take day.

In the meantime, I suspect just commenting that line out:
```
# csv.field_size_limit(sys.maxsize)
```

Should work. It's not necessary for the vast majority of use cases.

**Comment by ssnn-airr** [comment]
**Original comment by Jason Vander Heiden (Bitbucket: [javh](https://bitbucket.org/javh), GitHub: [javh](https://github.com/javh)).**

----------------------------------------

This should now be fixed as of fd501c1. You can install directly from bitbucket via:

```
pip install hg+https://bitbucket.org/kleinstein/changeo#default --upgrade --no-deps --force-reinstall
```

You may have to install [mercurial for windows](https://www.mercurial-scm.org/wiki/Download#Windows) first.

Let me know it still gives you trouble.

**Comment by ssnn-airr** [comment]
**Original comment by Jason Vander Heiden (Bitbucket: [javh](https://bitbucket.org/javh), GitHub: [javh](https://github.com/javh)).**

----------------------------------------

No news is good news.

**Comment by ssnn-airr** [comment]
**Original comment by Eric Mukherjee (Bitbucket: [emukherj](https://bitbucket.org/emukherj), ).**

----------------------------------------

Hey sorry my laptop is in the shop; ill let you know if it works when i get
back
