### ISSUE TITLE
IMGT changed column name from "Functionality" to "V-DOMAIN Functionality"

### ISSUE THREAD

**Issue by ssnn-airr** [immcantation/changeo#96]
**[Original report](https://bitbucket.org/kleinstein/changeo/issues/96) by Lisa Blum (Bitbucket: [LKBlum](https://bitbucket.org/LKBlum), GitHub: [LKBlum](https://github.com/LKBlum)).**

----------------------------------------

I ran "MakeDb.py imgt -i IMGTfile_out.txz -s IMGTfile_in.fasta" and got the following error: 

Traceback (most recent call last):
  File "/usr/local/bin/MakeDb.py", line 1393, in <module>
    args.func(**args_dict)
  File "/usr/local/bin/MakeDb.py", line 1153, in parseIMGT
    out_args=out_args)
  File "/usr/local/bin/MakeDb.py", line 992, in writeDb
    for record in db_gen:
  File "/usr/local/bin/MakeDb.py", line 554, in readIMGT
    if 'No results' not in sm['Functionality']:
KeyError: 'Functionality'

It looks like "Functionality" and "Functionality comment" in the 1_Summary.txt file are now "V-DOMAIN Functionality" and  "V-DOMAIN Functionality comment", respectively. IMGT files # 2, 3, and 6 also have "Functionality" (now "V-DOMAIN Functionality") columns. No other headers appear to have changed. 

Thanks! 

Lisa

**Comment by ssnn-airr** [comment]
**Original comment by Lisa Blum (Bitbucket: [LKBlum](https://bitbucket.org/LKBlum), GitHub: [LKBlum](https://github.com/LKBlum)).**

----------------------------------------

Nevermind -- I think you fixed this, and I just hadn't updated properly.
